apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-controller
  labels:
    control-plane: controller
spec:
  selector:
    matchLabels:
      app: notification-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: notification-controller
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: manager
        image: fluxcd/notification-controller
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        ports:
          - containerPort: 9090
            name: http
          - containerPort: 9292
            name: http-webhook
          - containerPort: 8080
            name: http-prom
        env:
          - name: RUNTIME_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            port: http-prom
            path: /metrics
        args:
        - --watch-all-namespaces
        - --log-level=info
        - --log-json
        - --enable-leader-election
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
          - name: temp
            mountPath: /tmp
      volumes:
        - name: temp
          emptyDir: {}
